name: 'Update Kubernetes Deployment'
description: 'Updates a Kubernetes deployment YAML file with new image tag and digest'
inputs:
  repository-name:
    description: 'Name of the repository'
    required: true
  image-tag:
    description: 'New image tag'
    required: true
  image-digest:
    description: 'New image digest'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
  bitbucket-token:
    description: 'Bitbucket token'
    required: true
  bitbucket-username:
    description: 'Bitbucket username'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image-tag }}
    - ${{ inputs.image-digest }}
    - ${{ inputs.github-token }}
    - ${{ inputs.repository-name }}
    - ${{ inputs.bitbucket-token }}
    - ${{ inputs.bitbucket-username }}