name: "Slack Notification"
description: "Send Slack notifications with different messages for start, success, and failure."
inputs:
  type:
    description: "Type of notification: start, success, or failure."
    required: true
  webhook_url:
    description: "The Slack webhook URL to send the notification."
    required: true
  stack_invoke:
    description: "Used to define which file is used in notify"
    required: false
    default: "none"
  pipeline_info: 
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: "Determine JSON File"
      id: select-json
      run: |
        case "${{ inputs.type }}" in
          start)
            json_file="${GITHUB_ACTION_PATH}/start.json"
            ;;
          success )
            if [ "${{ inputs.stack_invoke }}" == "mobile" ]; then
              json_file="${GITHUB_ACTION_PATH}/success-mobile.json"
            else
              json_file="${GITHUB_ACTION_PATH}/success.json"
            fi
            ;;
          failure)
            json_file="${GITHUB_ACTION_PATH}/failure.json"
            ;;
          *)
            echo "Invalid notification type" && exit 1
            ;;
        esac
        echo "json_file=$json_file" >> $GITHUB_ENV
        echo "json_file: $json_file"
      shell: bash

    - name: "Send Slack Notification"
      env:
        JSON_FILE: ${{ env.json_file }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_COMMIT_HASH: ${{ github.sha }}
        ADDITIONAL_INFO: ${{ inputs.pipeline_info }}
      run: |
        if [ ! -f "$JSON_FILE" ]; then
          echo "Error: JSON file not found at $JSON_FILE"
          exit 1
        fi
        
        REPO_NAME=$(basename ${{ github.repository }})
        BRANCH_NAME=$(basename ${{ github.ref }})
        COMMIT_SHORT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
        
        export REPO_NAME
        export BRANCH_NAME
        export GITHUB_ACTOR
        export GITHUB_RUN_ID
        export COMMIT_SHORT_HASH
        export ADDITIONAL_INFO

        envsubst < "$JSON_FILE" > "temp.json"
  
        curl -X POST -H 'Content-type: application/json' \
        --data @"temp.json" "${{ inputs.webhook_url }}"
      shell: bash
