name: 'Build and Push Docker Image to GCR'
description: 'Builds and pushes a Docker image to Google Container Registry (GCR) based on the branch.'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  IMAGE_TAG:
    description: 'Tag da imagem Docker.'
  IMAGE_DIGEST:
    description: 'Digest da imagem Docker.'