name: Build and Push Docker Image

on:
  push:
    paths:
      - 'build-push-image/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use the Google Cloud registry
        run: |
          gcloud --quiet auth configure-docker
          
      - name: Build Docker image
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/build-push-image:latest"
          docker build -t $IMAGE ./build-push-image
          
      - name: Push Docker image to Google Container Registry
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/build-push-image:latest"
          docker push $IMAGE
