name: Build and Push Docker Image to GCP

on:
  push:
    paths:
      - 'build-push-image/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker s-docker.pkg.dev --quiet

      - name: Build and Push Docker image to Artifact Registry
        env:
          IMAGE_NAME: us-central1-docker.pkg.dev/bdsp-devtools/build-push-images/build-push-image:latest
        run: |
          docker build -t $IMAGE_NAME ./build-push-image
          docker push $IMAGE_NAME
